name: Validate and process Building Blocks
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  validate-and-process:
    name: Validate and process
    uses: opengeospatial/bblocks-postprocess/.github/workflows/validate-and-process.yml@master
    with:
      register_file: bblocks/build/register.json
      items_dir: bblocks/_sources
      generated_docs_path: bblocks/build/generateddocs
      base_url: https://ogcincubator.github.io/GeoPose/bblocks
      annotated_path: bblocks/build/annotated
      config_file: bblocks/bblocks-config.yaml
      test_outputs_path: bblocks/build/tests
      viewer_path: ./bblocks/
    #   sparql_username: sparql
    #   sparql_password: Secr3T